subscribe:
  topics: send-many,purchase
notifications:
  send_money:
    condition: $.type = p2p
    sender:
      channel: push
    mapping:
      userid: $.userid
      title: ${user.name} send ${amount} to $.destination.user_name
      subtitle: send many
      footer:
  recived_money:
    condition: $.type = p2p
    sender:
      channel: push
    mapping:
      userid: $.user_id
      title: ${user_name} send ${amount} to $.destination.user_name
      subtitle: recived money
      footer: $.creation_date
  purchase:
    condition: $.type = p2m
    sender:
      channel: email
    mapping:
      userid: user en recived_money
      title: ${user.name} le mandaste  ${tx.amount} a $.destinatiion.user_name
      subtitle: ${user.name} asdasd ${asdasd}
      footer: ${user.name} asdasd ${asdasd}
